# Generated by Django 4.1.4 on 2022-12-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='users_id',
            new_name='user',
        ),
    ]
