# Generated by Django 4.1.4 on 2022-12-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_proyecto_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ips',
            },
        ),
    ]
