# Generated by Django 4.1.4 on 2022-12-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_ips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ips',
            new_name='Ip',
        ),
    ]
