# Generated by Django 4.1.4 on 2022-12-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='updated_at',
        ),
    ]
